name: "Book Dash Checklist"
description: Book Dash Planning Checklist
title: "Book Dash checklist <DATE>"
labels: book_dash
body:
- type: markdown
  attributes:
    value: "This issue is for the event organisers, **if you are an applicant please use this form to submit your application: [add registration form link].** This application will likely take 30 minutes to complete. You can use this template document with all the questions to prepare your draft:[https://tinyurl.com/tw-bookdash-template](https://tinyurl.com/tw-bookdash-template) <-- make sure that this template has been updated."
- type: input
  id: date
  attributes:
    label: Date
    description: |
      What is the date of the book dash?
  validations:
    required: true
- type: input
  id: hub
  attributes:
    label: Local Hub?
    description: |
      Would you like to host a local hub during the Book Dash? We are also inviting interest from The Turing Way community members to host a local hub, see details and share your response via a separate Google form: [add registration form link] 
  validations:
    required: true
- type: checkboxes
  id: checklist1
  attributes:
    label:  Before the event
    description: 
    options:
      - label: Finalise dates based on the location and core team’s availability
      - label: Set up a form (see a template here) for application by updating the previous version of the form
      - label: Write a short description for online advertisement
      - label: Open a call for application as well as invite interest to join the committee
      - label: Announce in the newsletter and promote on Twitter at least 2-3 months in advance
      - label: Establish a Book Dash Planning committee by inviting returning members of the event
      - label: Close the application round in time (minimum 1 month ahead of the event)
      - label: Set-up a form for reviewing applications (see Rubrics for scoring applications for details)
      - label: Set up an online platform (Zoom, or other accessible software) for remote collaboration
      - label: Copy the HackMD index page for the event using last round for reference [link](https://hackmd.io/@turingway/bookdash-nov2022-index)
      - label: Update shared HackMD for pre-event calls, book dash event and feedback
      - label: Copy the Eventbrite page from last round for the Book Dash attendees - set a registration code
      - label: Send a reminder in next newsletters with more details if needed
      - label: Copy the share out Eventbrite page (2 sessions)
      - label: Clearly state the following information in an application form and later communicate by email with the selected participants
      - label: What financial support will be available for either online or in-person events
      - label: What arrangements will be available online (such as online helpers and designated mentors) or on-site (such as quiet room and child care) for in-person events
      - label: Include accessibility information such as live captioning for in-person events and quiet room/child nursing room for in-person events
      - label: Mention the maximum limit for financial support requests for online (such as for headphones) and in-person (such as for travel and accommodation) events
- type: checkboxes
  id: checklist2
  attributes:
    label:  During and after the application phase
    description: 
    options:
      - label: Set up the Book Dash Planning meeting to discuss these details before the announcement is sent out
      - label: Discuss with co-organisers if some resources (such as email drafts or templates) need to be updated
      - label: Find volunteers from the organisers who would like to host onboarding calls (1 week before the event)
      - label: Find volunteers from the organisers who would like to host a GitHub introduction session (1 week before the event)
      - label: Find volunteers from the organisers who would like to run social events (discussion session, meal, informal chat)
      - label: For during the event find volunteers from the organisers who would like to run community share out sessions - on the last day
      - label:  Check with them if there is anything else they would like to suggest or get involved in
      - label:  Think about who else needs to be invited, like Artists, speakers, more diverse participants
      - label: Identify helpers and mentors from the applicants and core members -- invite them
      - label: Review applications in a designated panel (Book Dash Planning Committee) using Book Dash Rubrics for selection
      - label: Set up another meeting with the Book Dash Planning Committee to discuss the applications and finalise the selection
      - label: Use this meeting to also allocate tasks for during and after the event (indicate that on the GitHub issues)
- type: checkboxes
  id: checklist3
  attributes:
    label: After the selection phase
    description: 
    options:
      - label: Send an email to the selected attendees with Eventbrite page and registration code
      - label: Send an email to the unselected attendees with feedback
      - label: Set up an email chain and a Slack channel to connect all members and share updates
      - label: Provide details on Code of Conduct, contribution guideline and ways to get involved in an ongoing discussion
      - label: Update presentation for introducing the project to the participants on day-1 of the Book Dash
      - label: Host the onboarding call one week before the event to share logistics and facilitate the drafting of SMART goals
      - label: Group participants into the proposed working groups as per their SMART goals from the onboarding call
      - label: Send a reminder email to register on Eventbrite sharing important links and information including support grant, GitHub session, onboarding call info and reimbursement process
      - label: Create a GitHub issue to collect bio and highlight of the participants to add them to the Contributors Record
- type: checkboxes
  id: checklist4
  attributes:
    label: Additional tasks for an online event
    description: 
    options:
      - label: Set up a Slack channel and invite all attendees
      - label: Share all notes, agenda and info by email, and pin on the Slack channel
      - label: State the prerequisites to attend the event
      - label: An active GitHub account
      - label: Participation in at least one pre-event onboarding call or a Collaboration Cafe
      - label: Some experience with using GitHub or attend the Book Dash GitHub session
      - label: Familiarity with The Turing Way contribution guidelines and Code of Conduct
      - label: Willingness to collaborate with others
      - label: Ask them to choose at least one contribution session (2.5 hours) for each day of the Book Dash to ensure flexibility (rather than blocking the full day) -- this is for everyone joining online (see in person participation requirement below)
      - label: Collect address if something needs to be posted
- type: checkboxes
  id: checklist5
  attributes:
    label:  Additional tasks for an in-person event - local hubs
    description: 
    options:
      - label: Book location for in-person events
      - label: Collate participants’ preference for travel, meal, accommodation, and accessibility request through the registration form
      - label: Send an email to the participants regarding their travel, accommodation, schedule, and meal
      - label: Book catering for lunch and coffee breaks
      - label: Double-check with each participant if their plan as given on their registration hasn’t changed       
- type: checkboxes
  id: checklist6
  attributes:
    label:  When funding for travel and accommodation is available
    description: 
    options:
      - label: Book hotels rooms for people who requested accommodation
      - label: Book travel for those who requested - or provide reimbursement option
      - label: Double-check the details for travel and accommodation with each participant
      - label: Book meals/catering for people
      - label: Mention what meals will be offered as default - and ask participants to get in touch if another meal type is required
- type: checkboxes
  id: checklist7
  attributes:
    label: During the event
    description: 
    options:
      - label: "**Run onboarding sessions on the first day**"
      - label: Welcome everyone (for each slot)
      - label: Ask to fill the icebreaker
      - label: One of the organisers delivers introduction talk
      - label: Create breakout groups for people working on
      - label: "**Host coworking sessions with Pomodoro sessions 30-35 mins long**"
      - label: At the beginning of the session, ask people to document or verbally share their plan for the session
      - label: End each session with any report people want to make
      - label: Give 5 minutes break before entering the next Pomodoro
      - label: Keep last 10 minutes for final reporting and co-documenting the work that took place during the Pomodoro
      - label: If an artist, illustrator or consultant is invited, coordinate the schedule with participants so they have the chance to engage
      - label: Run a social session each day. These are run by organisers to ensure everyone has the chance to connect informally
      - label: Host community share out the event on the last day to demonstrate and celebrate the contributions made by everyone during the Book Dash
      - label: Ask for feedback on the last day (plus and delta)
      - label: Share the GitHub issue for adding bio and highlight
      - label: Take screenshots or group photos (with permission) to share in reports or social media
- type: checkboxes
  id: checklist8
  attributes:
    label: After the event
    description: 
    options:
      - label: Send a thank you email to everyone for their work
      - label: Move bio and highlight from the GitHub issue to the Contributors Record
      - label: Summarise the event (number of pull requests, issue, chapters, and other significant news) to share with the participants
      - label: Share the update via the newsletter
      - label: Develop a report with highlights and updates on GitHub
      - label: Set up a debrief meeting with the planning committee
      - label: Send a thank you note (or a package when possible) to the planning committee
